structure(list(indicator = c("Adults with HIV (%, age 15-49)", 
"Age at 1st marriage (women)", "Aged 15+ employment rate (%)", 
"Aged 15+ labour force participation rate (%)", "Aged 15+ unemployment rate (%)", 
"Aged 15-24 employment rate (%)", "Aged 15-24 unemployment rate (%)", 
"Aged 15-64 labour force participation rate (%)", "Aged 25-54 labour force participation rate (%)", 
"Aged 25-54 unemployment rate (%)", "Aged 55+ unemployment rate (%)", 
"Aged 65+ labour force participation rate (%)", "Agricultural land (% of land area)", 
"Agricultural water withdrawal (% of total)", "Agriculture (% of GDP)", 
"Agriculture workers (% of labour force)", "Aid given (% of GNI)", 
"Aid given (2007 US$)", "Aid given per person (2007 US$)", "Aid received (% of GNI)", 
"Aid received per person (current US$)", "Aid received, total (US$, inflation-adjusted)", 
"Alcohol consumption per adult 15+ (litres)", "All causes deaths in children 1-59 months (per 1,000 births)", 
"All causes deaths in children 1-59 months (total deaths)", "All causes deaths in newborn (per 1,000 births)", 
"All causes deaths in newborn (total deaths)", "All forms of TB, deaths per 100,000 - estimated", 
"All forms of TB, detection rate (%) ", "All forms of TB, detection rate (%) - DOTS only", 
"All forms of TB, existing cases per 100,000 - estimated", "All forms of TB, new cases per 100,000 - estimated", 
"All forms of TB, new cases per 100,000 - reported", "All forms of TB, number of deaths - estimated", 
"All forms of TB, number of existing cases - estimated", "All forms of TB, number of new cases - estimated", 
"All forms of TB, number of new cases - reported", "Alternative GDP per capita PPP, PWT 7.1", 
"Alternative GDP per capita PPP, WB", "Alternative GDP/capita (PPP$, inflation-adjusted) from PWT", 
"Alternative poverty (% below nationally defined poverty line)", 
"Annual HIV deaths (number, all ages)", "Armed forces personnel (% of labor force)", 
"Armed forces personnel, total", "Arms exports (US$, inflation-adjusted)", 
"Arms imports (US$, inflation adjusted)", "ART coverage % (CD4 < 350)", 
"Average age of dollar billionaires (years)", "Bad teeth per child (12 yr)", 
"Battle deaths (per 100 000)", "Biomass stock in forest (tons)", 
"Birth asphyxia deaths in newborn (per 1,000 births)", "Birth asphyxia deaths in newborn (total deaths)", 
"Births attended by skilled health staff (% of total)", "Blood pressure (SBP), men, mmHg", 
"Blood pressure (SBP), women, mmHg", "Body Mass Index (BMI), men, Kg/m2", 
"Body Mass Index (BMI), women, Kg/m2", "Breast cancer, deaths per 100,000 women", 
"Breast cancer, new cases per 100,000 women", "Breast cancer, number of female deaths", 
"Breast cancer, number of new female cases", "Broadband subscribers (per 100 people)", 
"Broadband subscribers (total)", "Burns deaths (per 100,000 people)", 
"Car deaths (per 100,000 people)", "Cars, trucks & buses per 1,000 persons", 
"Cell phones (per 100 people)", "Cell phones (total)", "Central bank discount rate (annual %)", 
"Cervical cancer, deaths per 100,000 women", "Cervical cancer, new cases per 100,000 women", 
"Cervical cancer, number of female deaths", "Cervical cancer, number of new female cases", 
"Child mortality (0-5 year-olds dying per 1,000 born)", "Children and elderly (per 100 adults)", 
"Children out of school, primary", "Children out of school, primary, female", 
"Children out of school, primary, male", "Children per woman (total fertility)", 
"Children per woman (total fertility), with projections", "Children per woman, temporary update", 
"Cholesterol (fat) in blood, men, mmol/L", "Cholesterol (fat) in blood, women, mmol/L", 
"CO2 emissions (tonnes per person)", "CO2 intensity of economic output (kg CO2 per 2005 PPP $ of GDP)", 
"Coal consumption, per person", "Coal consumption, total", "Colon&Rectum cancer, deaths per 100,000 men", 
"Colon&Rectum cancer, deaths per 100,000 women", "Colon&Rectum cancer, new cases per 100,000 men", 
"Colon&Rectum cancer, new cases per 100,000 women", "Colon&Rectum cancer, number of female deaths", 
"Colon&Rectum cancer, number of male deaths", "Colon&Rectum cancer, number of new female cases", 
"Colon&Rectum cancer, number of new male cases", "Congenital deaths in newborn (per 1,000 births)", 
"Congenital deaths in newborn (total deaths)", "Contraceptive use (% of women ages 15-49)", 
"Corruption Perception Index (CPI)", "Crude birth rate (births per 1,000 population)", 
"Crude death rate (deaths per 1,000 population)", "Cumulative CO2 emissions (tonnes)", 
"Data method - Maternal mortality", "Data quality - Children per woman", 
"Data quality - Income per person", "Data quality - Life expectancy", 
"Data quality - Population", "Dead kids per woman", "Debt servicing costs (% of exports and net income from abroad)", 
"Debt to foreigners by public & private (% of GNI)", "Democracy score (use as color)", 
"Desalinated water produced (billion cu meters)", "Diarrhoeal deaths in children 1-59 months (per 1,000 births)", 
"Diarrhoeal deaths in children 1-59 months (total deaths)", "Diarrhoeal deaths in newborn (per 1,000 births)", 
"Diarrhoeal deaths in newborn (total deaths)", "Dollar billionaires per million people", 
"Drought - affected annual number", "Drought - deaths annual number", 
"Drownings (per 100,000 people)", "DTP3 immunized (% of one-year-olds)", 
"Earthquake - affected annual number", "Earthquake - deaths annual number", 
"Economic growth over the past 10 years", "Economical infrastructure aid given (% of aid)", 
"Education aid given (% of aid)", "Electricity generation, per person", 
"Electricity generation, total", "Electricity use, per person", 
"Electricity use, total", "Energy from solid biofuels (%)", "Energy production, per person", 
"Energy production, total", "Energy supply per person TOE", "Energy use, per person", 
"Energy use, total", "Epidemic - affected annual number", "Epidemic - deaths annual number", 
"Estimate or projection of under-five mortality rate, from IHME", 
"Expenditure per student, primary (% of GDP per person)", "Expenditure per student, secondary (% of GDP per person)", 
"Expenditure per student, tertiary (% of GDP per person)", "Exports (% of GDP)", 
"Exports unit value (index, 2000=100)", "External debt, total (US$, not inflation-adjusted)", 
"Extreme poverty (% people below $1.25 a day)", "Extreme poverty (% people below $1.25 a day) version 20120905", 
"Extreme temperature - affected annual number", "Extreme temperature - deaths annual number", 
"Falls, deaths (per 100,000 people)", "Family workers (% of labour force)", 
"Female agriculture workers (% of female labour force)", "Female family workers (% of female labour force)", 
"Female industry workers (% of female labour force)", "Female long term unemployment rate (%)", 
"Female population, with projections", "Female salaried workers (% of female labour force)", 
"Female self-employed (% of female labour force)", "Female service workers (% of female labour force)", 
"Females aged 15+ employment rate (%)", "Females aged 15+ labour force participation rate (%)", 
"Females aged 15+, unemployment rate (%)", "Females aged 15-24 employment rate (%)", 
"Females aged 15-24, unemployment rate (%)", "Females aged 15-64 labour force participation rate (%)", 
"Females aged 25-54 labour force participation rate (%)", "Females aged 25-54, unemployment rate (%)", 
"Females aged 55+, unemployment rate (%)", "Females aged 65+ labour force participation rate (%)", 
"Fixed line and mobile phone subscribers (per 100 people)", "Flood - affected annual number", 
"Flood - deaths annual number", "Food supply (kilocalories / person & day)", 
"Foreign direct investment, net inflows (% of GDP)", "Foreign direct investment, net outflows (% of GDP)", 
"Forest area (sq. km)", "Forest coverage (%)", "Forest land, total area (ha)", 
"Forest products removal, per ha ($)", "Forest products removal, total ($)", 
"GDP/capita (US$, inflation-adjusted)", "GDP/capita growth (% per year)", 
"GDP/capita growth over next 10 years", "GDP/employee (US$, inflation-adjusted)", 
"GDP/working hour (US$, inflation-adjusted)", "GNI/capita (Atlas method, current US$)", 
"GNI/capita (constant 2000 US$)", "GNI/per capita (PPP, current international $)", 
"Government and society aid given (% of aid)", "Government health spending of total gov. spending (%)", 
"Government health spending per person (international $)", "Government health spending per person (US$)", 
"Government share of total health spending (%)", "HDI (Human Development Index)", 
"Health aid given (% of aid)", "HepB3 immunized (% of one-year-olds)", 
"Hib3 immunized (% of one-year-olds)", "High-technology exports (% of manufactured exports)", 
"HIV deaths in children 1-59 months (per 1,000 births)", "HIV deaths in children 1-59 months (total deaths)", 
"Hourly compensation (US$)", "How far to the north", "Hydroelectric electricity production, per person", 
"Hydroelectric electricity production, total", "IFPRI Underweight children", 
"Imports (% of GDP)", "Imports unit value (index, 2000=100)", 
"Improved sanitation, overall access (%)", "Improved sanitation, rural access (%)", 
"Improved sanitation, urban access (%)", "Improved water source, overall access (%)", 
"Improved water source, rural access (%)", "Improved water source, urban access (%)", 
"Income per person (GDP/capita, PPP$ inflation-adjusted)", "Income per person, with projections", 
"Income share of 2nd poorest 20%", "Income share of 2nd richest 20%", 
"Income share of middle 20%", "Income share of poorest 10%", 
"Income share of poorest 20%", "Income share of richest 10%", 
"Income share of richest 20%", "Industrial water withdrawal (% of total)", 
"Industry (% of GDP)", "Industry workers (% of labour force)", 
"Inequality index (Gini)", "Infant mortality (rate per 1,000 births)", 
"Infectious TB, detection rate (%)", "Infectious TB, detection rate (%) - DOTS only", 
"Infectious TB, new cases per 100,000 - estimated", "Infectious TB, new cases per 100,000 - reported", 
"Infectious TB, number of new cases - estimated", "Infectious TB, number of new cases - reported", 
"Infectious TB, treatment (DOTS) completed (%)", "Inflation (annual %)", 
"Injury deaths in children 1-59 months (per 1,000 births)", "Injury deaths in children 1-59 months (total deaths)", 
"Internal renewable water (cu meters per person)", "Internet users (per 100 people)", 
"Internet users (total)", "Investments (% of GDP)", "Life expectancy (years)", 
"Life expectancy at birth, temporary update", "Life expectancy at birth, with projections", 
"Literacy rate, adult female (% of females ages 15 and above)", 
"Literacy rate, adult male (% of males ages 15 and above)", "Literacy rate, adult total (% of people ages 15 and above)", 
"Literacy rate, youth female (% of females ages 15-24)", "Literacy rate, youth male (% of males ages 15-24)", 
"Literacy rate, youth total (% of people ages 15-24)", "Liver cancer, deaths per 100,000 men", 
"Liver cancer, deaths per 100,000 women", "Liver cancer, new cases per 100,000 men", 
"Liver cancer, new cases per 100,000 women", "Liver cancer, number of female deaths", 
"Liver cancer, number of male deaths", "Liver cancer, number of new female cases", 
"Liver cancer, number of new male cases", "Long term unemployment rate (%)", 
"Lung cancer, deaths per 100,000 men", "Lung cancer, deaths per 100,000 women", 
"Lung cancer, new cases per 100,000 men", "Lung cancer, new cases per 100,000 women", 
"Lung cancer, number of female deaths", "Lung cancer, number of male deaths", 
"Lung cancer, number of new female cases", "Lung cancer, number of new male cases", 
"Malaria cases per 100,000 - reported", "Malaria deaths in children 1-59 months (per 1,000 births)", 
"Malaria deaths in children 1-59 months (total deaths)", "Malaria deaths per 100,000 - reported", 
"Malaria number of cases - reported", "Malaria number of deaths - reported", 
"Male agriculture workers (% of male labour force)", "Male family workers (% of male labour force)", 
"Male industry workers (% of male labour force)", "Male long term unemployment rate (%)", 
"Male population, with projections", "Male salaried workers (% of male labour force)", 
"Male self-employed (% of male labour force)", "Male service workers (% of male labour force)", 
"Males aged 15+ employment rate (%)", "Males aged 15+ labour force participation rate (%)", 
"Males aged 15+, unemployment rate (%)", "Males aged 15-24 employment rate (%)", 
"Males aged 15-24, unemployment rate (%)", "Males aged 15-64 labour force participation rate (%)", 
"Males aged 25-54 labour force participation rate (%)", "Males aged 25-54, unemployment rate (%)", 
"Males aged 55+, unemployment rate (%)", "Males aged 65+ labour force participation rate (%)", 
"Malnutrition, weight for age (% of children under 5)", "Market value of listed companies (% of GDP)", 
"Maternal deaths, lifetime risk (per 1,000)", "Maternal deaths, total number", 
"Maternal mortality ratio (per 100,000 live births)", "Maternal mortality ratio WHO", 
"Math achievement - 4th grade", "Math achievement - 8th grade", 
"MCV immunized (% of one-year-olds)", "Mean years in school (men 25 to 34 years)", 
"Mean years in school (men 25 years and older)", "Mean years in school (women % men, 25 to 34 years)", 
"Mean years in school (women 25 to 34 years)", "Mean years in school (women 25 years and older)", 
"Mean years in school (women of reproductive age 15 to 44)", 
"Measles deaths in children 1-59 months (per 1,000 births)", 
"Measles deaths in children 1-59 months (total deaths)", "Median age (years)", 
"Medical Doctors (per 1,000 people)", "Meningitis deaths in children 1-59 months (per 1,000 births)", 
"Meningitis deaths in children 1-59 months (total deaths)", "Merchandise trade (% of GDP)", 
"Military expenditure (% of GDP)", "Motorcycle deaths (per 100,000 people)", 
"Multisector cross-cutting aid given (% of aid)", "Municipal water withdrawal (% of total)", 
"Municipal water withdrawal (cu meters per person)", "Murder (per 100,000 people)", 
"Murder (total deaths)", "Murdered 15-29 (per 100,000 people)", 
"Murdered 30-44, (per 100,000 people)", "Murdered 45-59 (per 100,000 people)", 
"Murdered 60+ (per 100,000 people)", "Murdered children 0-14 (per 100,000 people)", 
"Murdered men (per 100,000 people)", "Murdered women (per 100,000 people)", 
"Natural gas production, per person", "Natural gas production, total", 
"Natural gas proved reserves, total", "Natural gas proven reserves, per person", 
"NCD deaths in children 1-59 months (per 1,000 births)", "NCD deaths in children 1-59 months (total deaths)", 
"Net barter terms of trade (2000 = 100)", "New births (total number, estimated)", 
"Newly HIV infected (%, age 15-49)", "Newly HIV infected (number, all ages)", 
"Nuclear electricity production, per person", "Nuclear electricity production, total", 
"Number of child deaths", "Oil consumption, per person", "Oil consumption, total", 
"Oil production, per person", "Oil production, total", "Oil proved reserves, total", 
"Oil proven reserves, per person", "Old version of Income per person (version 3)", 
"Old version of Income per person (version 8)", "Other deaths in newborn (per 1,000 births)", 
"Other deaths in newborn (total deaths)", "Other infections deaths in children 1-59 months (per 1,000 births)", 
"Other infections deaths in children 1-59 months (total deaths)", 
"Other social services aid given (% of aid)", "Out-of-pocket share of total health spending (%)", 
"PAB immunized (% of newborns)", "Patent applications (total)", 
"Patents granted (total)", "Patents in force (total)", "People living with HIV (number, all ages)", 
"Personal computers (per 100 people)", "Personal computers (total)", 
"Pertussis deaths in children 1-59 months (per 1,000 births)", 
"Pertussis deaths in children 1-59 months (total deaths)", "Plane crash - affected annual number", 
"Plane crash - deaths annual number", "Planted forest area (ha)", 
"Pneumonia deaths in children 1-59 months (per 1,000 births)", 
"Pneumonia deaths in children 1-59 months (total deaths)", "Pneumonia deaths in newborn (per 1,000 births)", 
"Pneumonia deaths in newborn (total deaths)", "Poisonings, deaths (per 100,000 people)", 
"Population aged 0-4 years (total number)", "Population aged 0-4 years, both sexes (%)", 
"Population aged 0-4 years, female (%)", "Population aged 0-4 years, male (%)", 
"Population aged 10-14 years (total number)", "Population aged 10-14 years, both sexes (%)", 
"Population aged 10-14 years, female (%)", "Population aged 10-14 years, male (%)", 
"Population aged 15-19 years (total number)", "Population aged 15-19 years, both sexes (%)", 
"Population aged 15-19 years, female (%)", "Population aged 15-19 years, male (%)", 
"Population aged 20-39 years (total number)", "Population aged 20-39 years, both sexes (%)", 
"Population aged 20-39 years, female (%)", "Population aged 20-39 years, male (%)", 
"Population aged 40-59 years (total number)", "Population aged 40-59 years, both sexes (%)", 
"Population aged 40-59 years, female (%)", "Population aged 40-59 years, male (%)", 
"Population aged 5-9 years (total number)", "Population aged 5-9 years, both sexes (%)", 
"Population aged 5-9 years, female (%)", "Population aged 5-9 years, male (%)", 
"Population aged 60+ years (total number)", "Population aged 60+ years, both sexes (%)", 
"Population aged 60+ years, female (%)", "Population aged 60+ years, male (%)", 
"Population density (per square km)", "Population growth (annual %)", 
"Population growth (annual %), with projections", "Population in urban agglomerations > 1 million (% of total population)", 
"Population policies aid given (% of aid)", "Population, total", 
"Poverty (% people below $2 a day)", "Prematurity deaths in newborn (per 1,000 births)", 
"Prematurity deaths in newborn (total deaths)", "Present value of debt (% of GNI)", 
"Primary completion rate, total (% of relevant age group)", "Primary forest area (ha)", 
"Primary school completion (% of boys)", "Primary school completion (% of girls)", 
"Private share of total health spending (%)", "Privately owned forest land (%)", 
"Privately owned other wooded land (%)", "Production sector aid given (% of aid)", 
"Prostate cancer, deaths per 100,000 men", "Prostate cancer, new cases per 100,000 men", 
"Prostate cancer, number of male deaths", "Prostate cancer, number of new male cases", 
"Pump price for gasoline (US$ per liter)", "Ratio of girls to boys in primary and secondary education (%)", 
"Ratio of young literate females to males (% ages 15-24)", "Renewable water (cu meters per person)", 
"Residential electricity use, per person", "Residential electricity use, total", 
"Residential energy use (%)", "Roads, paved (% of total roads)", 
"Rural poverty (% rural people below national rural poverty line)", 
"Salaried workers (% of labour force)", "Self-employed (% of labour force)", 
"Sepsis deaths in newborn (per 1,000 births)", "Sepsis deaths in newborn (total deaths)", 
"Service workers (% of labour force)", "Services (% of GDP)", 
"Sex ratio (0-14 years)", "Sex ratio (15-24 years)", "Sex ratio (15-49 years)", 
"Sex ratio (above 50 years)", "Sex ratio (all age groups)", "Smoking adults (% of population over age 15)", 
"Smoking men (% of men over age 15) ", "Smoking women (% of women over age 15) ", 
"Stillbirths (per 1,000 births)", "Stomach cancer, deaths per 100,000 men", 
"Stomach cancer, deaths per 100,000 women", "Stomach cancer, new cases per 100,000 men", 
"Stomach cancer, new cases per 100,000 women", "Stomach cancer, number of female deaths", 
"Stomach cancer, number of male deaths", "Stomach cancer, number of new female cases", 
"Stomach cancer, number of new male cases", "Storm - affected annual number", 
"Storm - deaths annual number", "Subsistence incomes per person", 
"Sugar per person (g per day)", "Suicide (per 100,000 people)", 
"Suicide (total deaths)", "Suicide age 0-14 (per 100,000 people)", 
"Suicide age 15-29 (per 100,000 people)", "Suicide age 30-44 (per 100,000 people)", 
"Suicide age 45-59 (per 100,000 people)", "Suicide age 60+ (per 100,000 people)", 
"Suicide men (per 100,000 people)", "Suicide women (per 100,000 people)", 
"Sulfur emissions per person (kg)", "Surface area (sq. km)", 
"Surviving kids per woman", "Tax revenue (% of GDP)", "TB programme (DOTS) population coverage (%)", 
"TB with HIV+, deaths per 100,000 - estimated", "TB with HIV+, existing cases per 100,000 - estimated", 
"TB with HIV+, new cases per 100,000 - estimated", "TB with HIV+, number of deaths - estimated", 
"TB with HIV+, number of existing cases - estimated", "TB with HIV+, number of new cases - estimated", 
"Teen fertility rate (births per 1,000 women ages 15-19)", "Tetanus deaths in newborn (per 1,000 births)", 
"Tetanus deaths in newborn (total deaths)", "Total GDP (PPP$, inflation-adjusted)", 
"Total GDP (US$, inflation-adjusted)", "Total GNI (PPP, current international $)", 
"Total health spending (% of GDP)", "Total health spending per person (international $)", 
"Total health spending per person (US$)", "Total number of dollar billionaires", 
"Total population, with projections", "Total reserves (% of debt to foreigners)", 
"Total sulfur emission (kilotonnes)", "Total water withdrawal (billion cu meters)", 
"Trade balance (% of GDP)", "Trade balance (US$, not inflation-adjusted)", 
"Traffic (total deaths)", "Traffic deaths (per 100,000 people)", 
"Traffic deaths men (per 100,000 people)", "Traffic deaths women (per 100,000 people)", 
"Traffic mortality 15-29 (per 100,000 people)", "Traffic mortality 30-44 (per 100,000 people)", 
"Traffic mortality 45-59 (per 100,000 people)", "Traffic mortality 60+ (per 100,000 people)", 
"Traffic mortality children 0-14 (per 100,000 people)", "Tsunami - affected annual number", 
"Tsunami - deaths annual number", "Under-five mortality from CME (per 1,000 born)", 
"Under-five mortality from IHME (per 1,000 born)", "Underweight children", 
"Urban population", "Urban population (% of total)", "Urban population growth (annual %)", 
"Urban poverty (% urban people below national urban poverty line)", 
"Water and sanitation aid given (% of aid)", "Water withdrawal (cu meters per person)", 
"Wood removal (cubic meters)", "Working hours per week", "Year categorization 1820-2010", 
"Year categorization 1950-", "Yearly CO2 emissions (1000 tonnes)"
), provider = c("Based on UNAIDS", "Various sources", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "World Bank", "FAO aquastat database", 
"World Bank", "International Labour Organization", "OECD QWIDS", 
"OECD QWIDS", "OECD QWIDS", "World Bank", "World Bank", "World Bank", 
"WHO with additions", "Lancet", "Lancet", "Lancet", "Lancet", 
"World Health Organization", "World Health Organization", "World Health Organization", 
"World Health Organization", "World Health Organization", "World Health Organization", 
"World Health Organization", "World Health Organization", "World Health Organization", 
"World Health Organization", "PWT 7.1", "Word Bank", "PWT 6.2", 
"The World Bank", "UNAIDS", "WDI", "WDI", "World Bank", "World Bank", 
"UNAIDS", "Forbes", "WHO modified", "WHO", "FAO - Food and Agriculture Organization", 
"Lancet", "Lancet", "World Bank", "MRC-HPA Centre for Environment and Health", 
"MRC-HPA Centre for Environment and Health", "MRC-HPA Centre for Environment and Health", 
"MRC-HPA Centre for Environment and Health", "Based on IARC and WHO data", 
"Based on IARC data", "IARC", "IARC", "World Bank", "World Bank", 
"WHO", "XXX???", "World Bank", "World Bank", "World Bank", "UN Statistics Division", 
"Based on IARC and WHO data", "Based on IARC data", "IARC", "IARC", 
"Various sources", "UN data", "World Bank", "World Bank", "World Bank", 
"Various sources", "various sources", "Various sources", "MRC-HPA Centre for Environment and Health", 
"MRC-HPA Centre for Environment and Health", "CDIAC (Carbon Dioxide Information Analysis Center)", 
"World Bank", "BP", "BP", "Based on IARC and WHO data", "Based on IARC and WHO data", 
"Based on IARC data", "Based on IARC data", "IARC", "IARC", "IARC", 
"IARC", "Lancet", "Lancet", "World Bank", "Transparency International", 
"UN Population Division", "UN Population Division", "CDIAC (Carbon Dioxide Information Analysis Center)", 
"Hill et al", "Various sources", "Various sources", "Various sources", 
"Various sources", "Gapminder", "World Bank", "World Bank", "Polity IV project", 
"FAO aquastat database", "Lancet", "Lancet", "Lancet", "Lancet", 
"Forbes", "EM-DAT: The OFDA/CRED International Disaster Database", 
"EM-DAT: The OFDA/CRED International Disaster Database", "WHO", 
"UNICEF Childinfo", "EM-DAT: The OFDA/CRED International Disaster Database", 
"EM-DAT: The OFDA/CRED International Disaster Database", "Various sources", 
"OECD QWIDS", "OECD QWIDS", "BP", "BP", "BP", "World Bank", "Based on IEA data", 
"Based on WDI data", "World Bank", "Based on IEA", "World Bank", 
"World Bank", "EM-DAT: The OFDA/CRED International Disaster Database", 
"EM-DAT: The OFDA/CRED International Disaster Database", "Institute for Health Metrics and Evaluation", 
"World Bank", "World Bank", "World Bank", "World Bank", "World Bank", 
"World Bank", "The World Bank", "The World Bank", "EM-DAT: The OFDA/CRED International Disaster Database", 
"EM-DAT: The OFDA/CRED International Disaster Database", "WHO", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "UN Population Division", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "World Development Indicators", 
"EM-DAT: The OFDA/CRED International Disaster Database", "EM-DAT: The OFDA/CRED International Disaster Database", 
"FAO modified", "World Bank", "Not Found.", "World Bank", "FAO - Food and Agriculture Organization", 
"FAO - Food and Agriculture Organization", "FAO - Food and Agriculture Organization", 
"FAO - Food and Agriculture Organization", "World Bank", "World Bank", 
"Various sources", "International Labour Organization", "International Labour Organization", 
"World Bank ", "World Bank ", "World Bank ", "OECD QWIDS", "WHO Global Health Expenditure Database", 
"WHO Global Health Expenditure Database", "WHO Global Health Expenditure Database", 
"WHO Global Health Expenditure Database", "UNDP", "OECD QWIDS", 
"UNICEF Childinfo", "UNICEF Childinfo", "World Bank", "Lancet", 
"Lancet", "International Labour Organization", "Various sources", 
"World Bank", "World Bank", "World Bank", "World Bank", "World Bank", 
"World Bank", "World Bank", "World Bank", "MDG indicators", "MDG indicators", 
"MDG indicators", "Various sources", "Various sources", "The World Bank", 
"The World Bank", "The World Bank", "The World Bank", "The World Bank", 
"The World Bank", "The World Bank", "FAO aquastat database", 
"World Bank", "International Labour Organization", "The World Bank", 
"Various sources", "World Health Organization", "World Health Organization", 
"World Health Organization", "World Health Organization", "World Health Organization", 
"World Health Organization", "World Health Organization", "World Bank", 
"Lancet", "Lancet", "FAO aquastat database", "World Bank", "World Bank", 
"World Bank", "Various sources", "Various sources", "Various sources", 
"UNESCO Institute for Statistics", "UNESCO Institute for Statistics", 
"UNESCO Institute for Statistics", "UNESCO Institute for Statistics", 
"UNESCO Institute for Statistics", "UNESCO Institute for Statistics", 
"Based on IARC and WHO data", "Based on IARC and WHO data", "Based on IARC data", 
"Based on IARC data", "IARC", "IARC", "IARC", "IARC", "International Labour Organization", 
"Based on IARC and WHO data", "Based on IARC and WHO data", "Based on IARC data", 
"Based on IARC data", "IARC", "IARC", "IARC", "IARC", "World Health Organization", 
"Lancet", "Lancet", "World Health Organization", "World Health Organization", 
"World Health Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "UN Population Division", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "International Labour Organization", 
"International Labour Organization", "World Bank", "World Bank", 
"Unicef (Childinfo)", "various sources", "Various sources", "WHO", 
"TIMSS modified", "TIMSS modified", "UNICEF Childinfo", "IHME", 
"IHME", "IHME", "IHME", "IHME", "IHME", "Lancet", "Lancet", "UN Population Division", 
"World development indicators modified", "Lancet", "Lancet", 
"World Bank", "World Bank", "GIMD/WHO", "OECD QWIDS", "FAO aquastat database", 
"FAO aquastat database", "Various sources", "WHO Global Burden of Disease", 
"WHO", "WHO", "WHO", "WHO", "WHO", "WHO modified", "WHO modified", 
"BP", "BP", "BP", "BP", "Lancet", "Lancet", "World Bank", "Based on UN Population Division", 
"UNAIDS", "UNAIDS", "Not Found.", "World Bank", "Various sources", 
"BP", "BP", "BP", "BP", "BP", "BP", "Various sources", "Various sources", 
"Lancet", "Lancet", "Lancet", "Lancet", "OECD QWIDS", "Global Health Expenditure Database", 
"UNICEF Childinfo", "UN Statistics Division", "UN Statistics Division", 
"UN Statistics Division", "Based on UNAIDS", "UN data", "UN data", 
"Lancet", "Lancet", "EM-DAT: The OFDA/CRED International Disaster Database", 
"EM-DAT: The OFDA/CRED International Disaster Database", "FAO - Food and Agriculture Organization", 
"Lancet", "Lancet", "Lancet", "Lancet", "WHO", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "World Bank", "UN Population Division", 
"World Bank", "OECD QWIDS", "Various sources", "The World Bank", 
"Lancet", "Lancet", "World Bank", "World Bank", "FAO - Food and Agriculture Organization", 
"World Bank", "World Bank", "WHO Global Health Expenditure Database", 
"FAO - Food and Agriculture Organization", "FAO - Food and Agriculture Organization", 
"OECD QWIDS", "Based on IARC and WHO data", "Based on IARC data", 
"IARC", "IARC", "World Development Indicators", "World Bank", 
"World Bank", "FAO aquastat database", "IEA (International Energy Agency)", 
"IEA (International Energy Agency)", "Not Found.", "World Bank", 
"The World Bank", "International Labour Organization", "International Labour Organization", 
"Lancet", "Lancet", "International Labour Organization", "World Bank", 
"UN Population Division", "UN Population Division", "UN Population Division", 
"UN Population Division", "UN Population Division", "Based on WHOSIS data 2005", 
"Based on WHOSIS data 2005", "Based on WHOSIS data 2005", "Stanton etal with additions", 
"Based on IARC and WHO data", "Based on IARC and WHO data", "Based on IARC data", 
"Based on IARC data", "IARC", "IARC", "IARC", "IARC", "EM-DAT: The OFDA/CRED International Disaster Database", 
"EM-DAT: The OFDA/CRED International Disaster Database", "Various sources", 
"FAO modified", "WHO modified", "WHO Global Burden of Disease", 
"WHO", "WHO", "WHO", "WHO", "WHO", "WHO modified", "WHO modified", 
"Stern modified", "World Bank", "Gapminder", "World Bank", "World Health Organization", 
"World Health Organization", "World Health Organization", "World Health Organization", 
"World Health Organization", "World Health Organization", "World Health Organization", 
"Various sources", "Lancet", "Lancet", "Various sources", "World Bank", 
"World Bank ", " Global Health Expenditure Database modified", 
"WHO Global Health Expenditure Database", "WHO Global Health Expenditure Database", 
"Forbes", "Various sources", "World Bank", "Stern modified", 
"FAO aquastat database", "World Bank", "World Bank", "WHO with additions", 
"WHO modified", "WHO modified", "WHO modified", "WHO", "WHO", 
"WHO", "WHO", "WHO", "EM-DAT: The OFDA/CRED International Disaster Database", 
"EM-DAT: The OFDA/CRED International Disaster Database", "CME (Child Mortality Estimates Info)", 
"Institute for Health Metrics and Evaluation", "World Bank", 
"World Bank", "World Bank", "World Bank", "The World Bank", "OECD QWIDS", 
"FAO aquastat database", "FAO - Food and Agriculture Organization", 
"International Labour Organization", "Various sources", "Various sources", 
"CDIAC (Carbon Dioxide Information Analysis Center)"), category = c("Health", 
"Population", "Work", "Work", "Work", "Work", "Work", "Work", 
"Work", "Work", "Work", "Work", "Environment", "Environment", 
"Economy", "Work", "Economy", "Economy", "Economy", "Economy", 
"Economy", "Economy", "Health", "Health", "Health", "Health", 
"Health", "Health", "Health", "Health", "Health", "Health", "Health", 
"Health", "Health", "Health", "Health", "For advanced users", 
"For advanced users", "For advanced users", "For advanced users", 
"Health", "Society", "Society", "Economy", "Economy", "Health", 
"Economy", "Health", "Society", "Environment", "Health", "Health", 
"Health", "Health", "Health", "Health", "Health", "Health", "Health", 
"Health", "Health", "Infrastructure", "Infrastructure", "Health", 
"For advanced users", "Infrastructure", "Infrastructure", "Infrastructure", 
"Economy", "Health", "Health", "Health", "Health", "", "Population", 
"Education", "Education", "Education", "", "For advanced users", 
"For advanced users", "Health", "Health", "", "Environment", 
"Energy", "Energy", "Health", "Health", "Health", "Health", "Health", 
"Health", "Health", "Health", "Health", "Health", "Health", "Society", 
"Population", "Population", "Environment", "For advanced users", 
"For advanced users", "For advanced users", "For advanced users", 
"For advanced users", "For advanced users", "For advanced users", 
"Economy", "Society", "Environment", "Health", "Health", "Health", 
"Health", "Economy", "Environment", "Environment", "Health", 
"Health", "Environment", "Environment", "For advanced users", 
"Economy", "Economy", "Energy", "Energy", "Energy", "Energy", 
"For advanced users", "Energy", "Energy", "For advanced users", 
"Energy", "Energy", "Environment", "Environment", "For advanced users", 
"Education", "Education", "Education", "Economy", "For advanced users", 
"For advanced users", "Economy", "For advanced users", "Environment", 
"Environment", "Health", "Work", "Work", "Work", "Work", "Work", 
"For advanced users", "Work", "Work", "Work", "Work", "Work", 
"Work", "Work", "Work", "Work", "Work", "Work", "Work", "Work", 
"Infrastructure", "Environment", "Environment", "Health", "Economy", 
"Economy", "Environment", "Environment", "Environment", "Environment", 
"Environment", "Economy", "Economy", "Economy", "Economy", "Economy", 
"Economy", "Economy", "Economy", "Economy", "Health", "Health", 
"Health", "Health", "Society", "Economy", "Health", "Health", 
"Economy", "Health", "Health", "Economy", "For advanced users", 
"Energy", "Energy", "For advanced users", "Economy", "For advanced users", 
"Infrastructure", "Infrastructure", "Infrastructure", "Infrastructure", 
"Infrastructure", "Infrastructure", "", "For advanced users", 
"Economy", "Economy", "Economy", "Economy", "Economy", "Economy", 
"Economy", "Environment", "Economy", "Work", "Economy", "Health", 
"Health", "Health", "Health", "Health", "Health", "Health", "Health", 
"Economy", "Health", "Health", "Environment", "Infrastructure", 
"Infrastructure", "Economy", "", "For advanced users", "For advanced users", 
"Education", "Education", "Education", "Education", "Education", 
"Education", "Health", "Health", "Health", "Health", "Health", 
"Health", "Health", "Health", "Work", "Health", "Health", "Health", 
"Health", "Health", "Health", "Health", "Health", "Health", "Health", 
"Health", "Health", "Health", "Health", "Work", "Work", "Work", 
"Work", "For advanced users", "Work", "Work", "Work", "Work", 
"Work", "Work", "Work", "Work", "Work", "Work", "Work", "Work", 
"Work", "Health", "Economy", "Health", "Health", "Health", "For advanced users", 
"Education", "Education", "Health", "Education", "Education", 
"Education", "Education", "Education", "Education", "Health", 
"Health", "Population", "Health", "Health", "Health", "Economy", 
"Society", "For advanced users", "Economy", "Environment", "Environment", 
"Society", "Society", "For advanced users", "For advanced users", 
"For advanced users", "For advanced users", "For advanced users", 
"For advanced users", "For advanced users", "Energy", "Energy", 
"Energy", "Energy", "Health", "Health", "For advanced users", 
"Population", "Health", "Health", "Energy", "Energy", "Health", 
"Energy", "Energy", "Energy", "Energy", "Energy", "Energy", "For advanced users", 
"For advanced users", "Health", "Health", "Health", "Health", 
"Economy", "Health", "Health", "Economy", "Economy", "Economy", 
"Health", "Infrastructure", "Infrastructure", "Health", "Health", 
"Environment", "Environment", "Environment", "Health", "Health", 
"Health", "Health", "Health", "Population", "Population", "Population", 
"Population", "Population", "Population", "Population", "Population", 
"Population", "Population", "Population", "Population", "Population", 
"Population", "Population", "Population", "Population", "Population", 
"Population", "Population", "Population", "Population", "Population", 
"Population", "Population", "Population", "Population", "Population", 
"Population", "Population", "For advanced users", "Population", 
"Economy", "Population", "Economy", "Health", "Health", "For advanced users", 
"Education", "Environment", "Education", "Education", "Health", 
"Environment", "Environment", "Economy", "Health", "Health", 
"Health", "Health", "Energy", "Education", "Education", "Environment", 
"Energy", "Energy", "For advanced users", "Infrastructure", "Economy", 
"Work", "Work", "Health", "Health", "Work", "Economy", "Population", 
"Population", "Population", "Population", "Population", "Health", 
"Health", "Health", "Health", "Health", "Health", "Health", "Health", 
"Health", "Health", "Health", "Health", "Environment", "Environment", 
"For advanced users", "Health", "Health", "Health", "For advanced users", 
"For advanced users", "For advanced users", "For advanced users", 
"For advanced users", "For advanced users", "For advanced users", 
"Environment", "Environment", "For advanced users", "Economy", 
"Health", "Health", "Health", "Health", "Health", "Health", "Health", 
"Population", "Health", "Health", "Economy", "Economy", "Economy", 
"Health", "Health", "Health", "Economy", "For advanced users", 
"Economy", "Environment", "Environment", "Economy", "Economy", 
"Infrastructure", "Infrastructure", "For advanced users", "For advanced users", 
"For advanced users", "For advanced users", "For advanced users", 
"For advanced users", "For advanced users", "Environment", "Environment", 
"For advanced users", "For advanced users", "Health", "Population", 
"Population", "Population", "Economy", "Economy", "Environment", 
"Environment", "Economy", "For advanced users", "For advanced users", 
"Environment"), subcategory = c("HIV", "", "Employment rate", 
"Labour force participation", "Unemployment", "Employment rate", 
"Unemployment", "Labour force participation", "Labour force participation", 
"Unemployment", "Unemployment", "Labour force participation", 
"Geography", "Water", "Sectors", "Employment by sector", "Aid given", 
"Aid given", "Aid given", "Aid received", "Aid received", "Aid received", 
"Risk factors", "Causes of child deaths", "Causes of child deaths", 
"Causes of newborn deaths", "Causes of newborn deaths", "TB (tuberculosis)", 
"TB (tuberculosis)", "TB (tuberculosis)", "TB (tuberculosis)", 
"TB (tuberculosis)", "TB (tuberculosis)", "TB (tuberculosis)", 
"TB (tuberculosis)", "TB (tuberculosis)", "TB (tuberculosis)", 
"Alternative GDP data", "Alternative GDP data", "Alternative GDP data", 
"Alternative poverty measures", "HIV", "War & peace", "War & peace", 
"Debt & trade", "Debt & trade", "HIV", "Poverty & inequality", 
"Teeth", "War & peace", "Forestry", "Causes of newborn deaths", 
"Causes of newborn deaths", "Maternal health", "Risk factors", 
"Risk factors", "Risk factors", "Risk factors", "Cancer, female", 
"Cancer, female", "Cancer, female", "Cancer, female", "Communication", 
"Communication", "Injuries and accidents", "Injury deaths by gender, age, road user", 
"Traffic", "Communication", "Communication", "Economic situation", 
"Cancer, female", "Cancer, female", "Cancer, female", "Cancer, female", 
"", "", "School enrolment", "School enrolment", "School enrolment", 
"", "Projections", "Alternative demography indicators", "Risk factors", 
"Risk factors", "", "Emissions", "Coal", "Coal", "Cancer, male", 
"Cancer, female", "Cancer, male", "Cancer, female", "Cancer, female", 
"Cancer, male", "Cancer, female", "Cancer, male", "Causes of newborn deaths", 
"Causes of newborn deaths", "Maternal health", "", "Population growth", 
"Population growth", "Emissions", "Data quality (use as color)", 
"Data quality (use as color)", "Data quality (use as color)", 
"Data quality (use as color)", "Data quality (use as color)", 
"families", "Advanced debt & trade", "Debt & trade", "", "Water", 
"Causes of child deaths", "Causes of child deaths", "Causes of newborn deaths", 
"Causes of newborn deaths", "Poverty & inequality", "Disasters", 
"Disasters", "Injuries and accidents", "Vaccine", "Disasters", 
"Disasters", "Economic growth", "Aid given", "Aid given", "Electricity", 
"Electricity", "Electricity", "Electricity", "Alternative energy", 
"Total", "Total", "Alternative energy", "Total", "Total", "Disasters", 
"Disasters", "Data quality (use as color)", "Schooling cost", 
"Schooling cost", "Schooling cost", "Debt & trade", "Advanced debt & trade", 
"Advanced debt & trade", "Poverty & inequality", "Alternative poverty measures", 
"Disasters", "Disasters", "Injuries and accidents", "Employment by status", 
"Employment by sector", "Employment by status", "Employment by sector", 
"Unemployment", "Projections", "Employment by status", "Employment by status", 
"Employment by sector", "Employment rate", "Labour force participation", 
"Unemployment", "Employment rate", "Unemployment", "Labour force participation", 
"Labour force participation", "Unemployment", "Unemployment", 
"Labour force participation", "Communication", "Disasters", "Disasters", 
"Nutrition", "Economic situation", "Economic situation", "Geography", 
"Forestry", "Forestry", "Forestry", "Forestry", "Incomes & growth", 
"Incomes & growth", "Incomes & growth", "Incomes & growth", "Incomes & growth", 
"Incomes & growth", "Incomes & growth", "Incomes & growth", "Aid given", 
"Health Economics", "Health Economics", "Health Economics", "Health Economics", 
"", "Aid given", "Vaccine", "Vaccine", "Debt & trade", "Causes of child deaths", 
"Causes of child deaths", "Economic situation", "Geography and infrastructure", 
"Hydro", "Hydro", "", "Debt & trade", "Advanced debt & trade", 
"Sanitation", "Sanitation", "Sanitation", "Water", "Water", "Water", 
"", "Projections", "Poverty & inequality", "Poverty & inequality", 
"Poverty & inequality", "Poverty & inequality", "Poverty & inequality", 
"Poverty & inequality", "Poverty & inequality", "Water", "Sectors", 
"Employment by sector", "Poverty & inequality", "", "TB (tuberculosis)", 
"TB (tuberculosis)", "TB (tuberculosis)", "TB (tuberculosis)", 
"TB (tuberculosis)", "TB (tuberculosis)", "TB (tuberculosis)", 
"Economic situation", "Causes of child deaths", "Causes of child deaths", 
"Water", "Communication", "Communication", "Economic situation", 
"", "Alternative demography indicators", "Projections", "Literacy", 
"Literacy", "Literacy", "Literacy", "Literacy", "Literacy", "Cancer, male", 
"Cancer, female", "Cancer, male", "Cancer, female", "Cancer, female", 
"Cancer, male", "Cancer, female", "Cancer, male", "Unemployment", 
"Cancer, male", "Cancer, female", "Cancer, male", "Cancer, female", 
"Cancer, female", "Cancer, male", "Cancer, female", "Cancer, male", 
"Malaria", "Causes of child deaths", "Causes of child deaths", 
"Malaria", "Malaria", "Malaria", "Employment by sector", "Employment by status", 
"Employment by sector", "Unemployment", "Projections", "Employment by status", 
"Employment by status", "Employment by sector", "Employment rate", 
"Labour force participation", "Unemployment", "Employment rate", 
"Unemployment", "Labour force participation", "Labour force participation", 
"Unemployment", "Unemployment", "Labour force participation", 
"Nutrition", "Economic situation", "Maternal health", "Maternal health", 
"Maternal health", "Alternative health data", "Achievement", 
"Achievement", "Vaccine", "Mean years in school", "Mean years in school", 
"Mean years in school", "Mean years in school", "Mean years in school", 
"Mean years in school", "Causes of child deaths", "Causes of child deaths", 
"", "Health Economics", "Causes of child deaths", "Causes of child deaths", 
"Debt & trade", "War & peace", "Injury deaths by gender, age, road user", 
"Aid given", "Water", "Water", "", "", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Natural gas", "Natural gas", "Natural gas", "Natural gas", "Causes of child deaths", 
"Causes of child deaths", "Advanced debt & trade", "Population growth", 
"HIV", "HIV", "Nuclear", "Nuclear", "", "Oil", "Oil", "Oil", 
"Oil", "Oil", "Oil", "Alternative GDP data", "Alternative GDP data", 
"Causes of newborn deaths", "Causes of newborn deaths", "Causes of child deaths", 
"Causes of child deaths", "Aid given", "Health Economics", "Vaccine", 
"Economic situation", "Economic situation", "Economic situation", 
"HIV", "Communication", "Communication", "Causes of child deaths", 
"Causes of child deaths", "Disasters", "Disasters", "Forestry", 
"Causes of child deaths", "Causes of child deaths", "Causes of newborn deaths", 
"Causes of newborn deaths", "Injuries and accidents", "Both sexes by age (total)", 
"Both sexes by age (%)", "Female by age (%)", "Male by age (%)", 
"Both sexes by age (total)", "Both sexes by age (%)", "Female by age (%)", 
"Male by age (%)", "Both sexes by age (total)", "Both sexes by age (%)", 
"Female by age (%)", "Male by age (%)", "Both sexes by age (total)", 
"Both sexes by age (%)", "Female by age (%)", "Male by age (%)", 
"Both sexes by age (total)", "Both sexes by age (%)", "Female by age (%)", 
"Male by age (%)", "Both sexes by age (total)", "Both sexes by age (%)", 
"Female by age (%)", "Male by age (%)", "Both sexes by age (total)", 
"Both sexes by age (%)", "Female by age (%)", "Male by age (%)", 
"", "Population growth", "Projections", "Urbanization", "Aid given", 
"", "Poverty & inequality", "Causes of newborn deaths", "Causes of newborn deaths", 
"Advanced debt & trade", "School enrolment", "Forestry", "School enrolment", 
"School enrolment", "Health Economics", "Forestry", "Forestry", 
"Aid given", "Cancer, male", "Cancer, male", "Cancer, male", 
"Cancer, male", "", "Gender equality", "Gender equality", "Water", 
"Electricity", "Electricity", "Alternative energy", "Traffic", 
"Poverty & inequality", "Employment by status", "Employment by status", 
"Causes of newborn deaths", "Causes of newborn deaths", "Employment by sector", 
"Sectors", "Sex ratio", "Sex ratio", "Sex ratio", "Sex ratio", 
"Sex ratio", "Risk factors", "Risk factors", "Risk factors", 
"Maternal health", "Cancer, male", "Cancer, female", "Cancer, male", 
"Cancer, female", "Cancer, female", "Cancer, male", "Cancer, female", 
"Cancer, male", "Disasters", "Disasters", "Alternative GDP data", 
"Nutrition", "Mental health", "Mental health", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Emissions", "Geography", "families", "Economic situation", "TB (tuberculosis)", 
"TB (tuberculosis)", "TB (tuberculosis)", "TB (tuberculosis)", 
"TB (tuberculosis)", "TB (tuberculosis)", "TB (tuberculosis)", 
"Population growth", "Causes of newborn deaths", "Causes of newborn deaths", 
"Incomes & growth", "Incomes & growth", "Incomes & growth", "Health Economics", 
"Health Economics", "Health Economics", "Poverty & inequality", 
"Projections", "Debt & trade", "Emissions", "Water", "Debt & trade", 
"Debt & trade", "Traffic", "Traffic", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Injury deaths by gender, age, road user", "Injury deaths by gender, age, road user", 
"Disasters", "Disasters", "Alternative child mortality data", 
"Alternative child mortality data", "", "Urbanization", "Urbanization", 
"Urbanization", "Poverty & inequality", "Aid given", "Water", 
"Forestry", "Economic situation", "Years (use as color)", "Years (use as color)", 
"Emissions"), link = c("http://spreadsheets.google.com/pub?key=pyj6tScZqmEfbZyl0qjbiRQ&output=csv", 
"http://spreadsheets.google.com/pub?key=t4eF8H_jq_xyKCUHAX6VT1g&output=csv", 
"http://spreadsheets.google.com/pub?key=rV0ksExNqh6V_h40f0_nFjg&output=csv", 
"http://spreadsheets.google.com/pub?key=ryyQX_1TXlohXWOSUswhIKg&output=csv", 
"http://spreadsheets.google.com/pub?key=rlD36wGmkwFt3ED558waCTQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rfHz_nx27dDQo4dUoIeVT3A&output=csv", 
"http://spreadsheets.google.com/pub?key=rb0oP4d1BREXa8xMIUf4NZg&output=csv", 
"http://spreadsheets.google.com/pub?key=rx1TECfEnGlnomonxCCO-Aw&output=csv", 
"http://spreadsheets.google.com/pub?key=rTrB-PY0sfM_gdAQ20XovfA&output=csv", 
"http://spreadsheets.google.com/pub?key=rEMA-cbNPaOtpDyxTcwugnw&output=csv", 
"http://spreadsheets.google.com/pub?key=rNn0y3e0bCpaqTM_8BVZBdg&output=csv", 
"http://spreadsheets.google.com/pub?key=r1hlZB_n1rpXTij11Kw7lTQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEF3alRGS0JQZVgwSW1FWUxUQmZoWXc&output=csv", 
"http://spreadsheets.google.com/pub?key=rab3jHe_JZrU1pqlX0xnQEw&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFhPbDdCTTYxM1dGc21UdE9sSkp1WEE&output=csv", 
"http://spreadsheets.google.com/pub?key=rzFD5mOuB5mR7-vLoP04LAQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tQR7RhlZdPjBkVCDPPF4zUg&output=csv", 
"http://spreadsheets.google.com/pub?key=tFOn62dEO9QCyIKK6kgSYRQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tGTst0WEm8V8zI9LOYvGmTg&output=csv", 
"http://spreadsheets.google.com/pub?key=tzK6dx2JltRfVXFI1ADh84w&output=csv", 
"http://spreadsheets.google.com/pub?key=t9GL1nIZdtxszJbjKErN2Hg&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHVuNVpKdnNCa08yV3NOd0Zsal9JaWc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldGJqTDRfNHBWODJMRWlZaVhNclhNZXc&output=csv", 
"http://spreadsheets.google.com/pub?key=t9FP3_OPrE2ug_I_iNsbePg&output=csv", 
"http://spreadsheets.google.com/pub?key=taYeez4Mkk8OvdH-q4QAxxQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tbpc_fYEqPzaE7pDWBG84Rw&output=csv", 
"http://spreadsheets.google.com/pub?key=tBVcAKWEbc2s687q6D9yuYg&output=csv", 
"http://spreadsheets.google.com/pub?key=rWM9yEzjpGJvcJlUAIm35tA&output=csv", 
"http://spreadsheets.google.com/pub?key=ru195-zJ0rsx5axPIvm_bRA&output=csv", 
"http://spreadsheets.google.com/pub?key=rutVwqgB14uRV_f2dRbqhUA&output=csv", 
"http://spreadsheets.google.com/pub?key=rZNoyaocUmUGuFyRgjJUpig&output=csv", 
"http://spreadsheets.google.com/pub?key=rMsQHawTObBb6_U2ESjKXYw&output=csv", 
"http://spreadsheets.google.com/pub?key=rYICvtvVz28fVyQuG_ote2w&output=csv", 
"http://spreadsheets.google.com/pub?key=rrQ_y5fqQPlznp5mJGXWr-A&output=csv", 
"http://spreadsheets.google.com/pub?key=rOCGMcGcrZs-dfeTEC792ZQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rhZayTbvH3ZLlSN64OuRYFg&output=csv", 
"http://spreadsheets.google.com/pub?key=r5UikGjnZlemlelKY0NX9Pg&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArtujvvFrPjVdEhhbV90QlJ3RFM0TW83dHd6RXBiX3c&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArtujvvFrPjVdERlTHZFQ2ZaUkpySHpQMF82UmdlcUE&output=csv", 
"http://spreadsheets.google.com/pub?key=tSUr_yZVbM6a3AGJEq_Z2Pw&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEd1R9UmohEIaA&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdHZJdFBhYVlvck43d1R6ZFYzUWpiLWc&output=csv", 
"http://spreadsheets.google.com/pub?key=0Asm_G8nr4TCSdFFoVWRjcUdKZDFydGdGNXkzS2ZRbHc&output=csv", 
"http://spreadsheets.google.com/pub?key=0Asm_G8nr4TCSdG1nNjk5RzItcUp6N2dSdHUwOENXa0E&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdGpkU3BSVmw5UXhTMWd6UFc1eXI3Rnc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEljeENrOXlFXzR3Rm8xT0drTV9YclE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdHMzRDA5Z1RjWkJIWkNfdWNBVFR6b1E&output=csv", 
"http://spreadsheets.google.com/pub?key=t_KhYe1qTGh4c90N61AUDSg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3Os9LVO_pRDA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldElMWEl4RFVTemlMbzJqRU50ZDJ3SHc&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWcsSl830EklJA&output=csv", 
"http://spreadsheets.google.com/pub?key=t_0WcTuc94YT9cJVvy1tmUg&output=csv", 
"http://spreadsheets.google.com/pub?key=twrll6eL8GeIU4P71aTakmg&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdF9OQ2dSSG5nNFhpS3RnRVZHUzZMb3c&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdHNwRm9DN1FnT3hXWWZVSncxMkZyS2c&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdHBzUVVSMDlTX1ZCUnNJQ3ZFdkFXVFE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdF9saE1pWUNYVkVsNU1FdW1Yem81Nmc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGt0elo2dzJMVVQ3WmFGSmdhc09LRlE&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3wJUwXXDdiGg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0Zbn8wVYsEHQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj07QB-Apx8RfQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2fGuJ1VdTpOw&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHdmMGVNNnV1SHBONDRTdTJzTVBKQXc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEpMTHBoMmNzcDVCNVRHWE5zSVJVRHc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldGloTm9wekpDcUdMUjhlYWFKaHdnVWc&output=csv", 
"http://spreadsheets.google.com/pub?key=tLf-4GD5z0QxqsDoUz4vOlg&output=csv", 
"http://spreadsheets.google.com/pub?key=tu0H0unnUriNvMXwH_qOqzw&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdG1MSjEyS0h2QjRQZ3FXRVR2dVQyeFE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEhWLWtqNzljbWg4ZXV6M09JQXNGaUE&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEejn8qHNmm4LQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0jPl21g3mqfQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3XpKHFksEPcA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2KBU_veE9AQg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0g-SgNTI23GQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCcGhBd2NOQVZ1eWowNVpSNjl1c3lRSWc&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2biT80zgTsYQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdGVSdkZnZWhfMDYybzd6U2p3NkxsZ3c&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFNPaEhiUDJ0QWZYOEwwQlBSTmtza1E&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFd5cnQzNU5IYm1vTWtrTWRIX3UxbHc&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0TAlJeCEzcGQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tGdhNYGTGtunwzkKJ9aRhsA&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFJCTm43NGc0SzdYeHBpZWZGb1V0ckE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdDU5SnRoQ0xlZWhwRUZ6RFNQV042enc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGJHcHZkSUdBcU56aS1OT3lLeU4tRHc&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1gkNuUEXOGag&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEVUcEJVRzlFWWRRcjhveGlrQzdwdUE&output=csv", 
"http://spreadsheets.google.com/pub?key=0Auk0ddvGIrGqcHlqNnRTY1pxbUVka1hObHlPbTlmUUE&output=csv", 
"http://spreadsheets.google.com/pub?key=0Auk0ddvGIrGqcHlqNnRTY1pxbUVjMVRtTWlGZG1PVmc&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0VhkB8-rRHQg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3bdzmKAvdUSw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2UBFFaFy3Ebg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2P7lqZXLeZAw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0ndPkFlozzXQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0-sqkfnD4rGA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2L5YHqVxRTLA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3nBOvEwrkMTA&output=csv", 
"http://spreadsheets.google.com/pub?key=tneegXfZGHA0-nLG25ypnyg&output=csv", 
"http://spreadsheets.google.com/pub?key=tUvFsKz2lGL-GtPmw47VLdg&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFp2OENYMUVKWnY1dkJLRXAtYnI3UVE&output=csv", 
"http://spreadsheets.google.com/pub?key=tKOphM3UPRd94T6C6pmsuXw&output=csv", 
"http://spreadsheets.google.com/pub?key=tUSeGJOQhafugwUvHvY-wLA&output=csv", 
"http://spreadsheets.google.com/pub?key=tHyj-2jRvK3CCNJOc5Vm-HQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEed4UamoiNCFA&output=csv", 
"http://spreadsheets.google.com/pub?key=thDxsgSWvLGW4M1qUBby7OQ&output=csv", 
"http://spreadsheets.google.com/pub?key=thlR4hyNMEnaVyV_uxRzjfQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0atjJIuxy-KQ&output=csv", 
"http://spreadsheets.google.com/pub?key=p8SIY47PNEw6vGCNzlYJ5eA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1ONZlWMf9KQA&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArtujvvFrPjVdDRQTUhzNmVySlp6djRtLWh4eS1sNHc&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEd-30XcArAJHA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdDlSTTVWUkU3Z254aEhERmVuQWZaeWc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGQ2YlhDSWVIdXdpMmhLY2ZZRHdNNnc&output=csv", 
"http://spreadsheets.google.com/pub?key=rt3BaikcRwJBNC0CvQsjDCA&output=csv", 
"http://spreadsheets.google.com/pub?key=tADSStUzP0ADEPYqsIfVHMQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tDzIq4iIDwNtYthN_QYZwZg&output=csv", 
"http://spreadsheets.google.com/pub?key=tX7NQAP_5H4TOS1OEnxdxYw&output=csv", 
"http://spreadsheets.google.com/pub?key=tKZcnGP_XImMXRZ4tZqtjMg&output=csv", 
"http://spreadsheets.google.com/pub?key=tAQpQeQkuyA1-ZovdDJ7JAw&output=csv", 
"http://spreadsheets.google.com/pub?key=rAYA0bjnfYwzXnir0cigijQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rvRwTPi0n_94EScVA3YjLeg&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldF9ZRnhuWWljUXJHRDRpb0cyaHNLSUE&output=csv", 
"http://spreadsheets.google.com/pub?key=txVTyScWObTBNuMmkNtLh1w&output=csv", 
"http://spreadsheets.google.com/pub?key=rG_BjsDwyS2n7DANNH3i5vQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rvbbs7uxQc7swJ4RR2BcQfA&output=csv", 
"http://spreadsheets.google.com/pub?key=tkdAnkbHJxPAlRX6P1mAh8w&output=csv", 
"http://spreadsheets.google.com/pub?key=tMxqFNS7BC5QyLrhBO8DXqQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tQQaILpdu-vGtSkJLr2VQCw&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEeMtYNdMyLKOw&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEehRG-9mMHYdg&output=csv", 
"http://spreadsheets.google.com/pub?key=tiVeyAJd7iRWorOwl_ARWEQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tEu78F4acf0u6MRyhg5-9qQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFdaNHA3R1BzcG9GSlkwMXdnMHpScVE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHJ6UTV4MkEyN0NYdnJJOG1oYUxmTWc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFNZMXZwcjNPY2c3MWwxbWIwVFgyd0E&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFFjMFlMeS02N1NGNjJabl8wamVtdHc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHRmYjJWLVF0SjlQY1N5Vm9yU0xxaGc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHd2Nld0NEVFOGRiSTc0V3ZoekNuS1E&output=csv", 
"http://spreadsheets.google.com/pub?key=r6H8dfVPu2CJ2nzI8X0jurw&output=csv", 
"http://spreadsheets.google.com/pub?key=rvtZF_JC0OI27tL66o6hiMQ&output=csv", 
"http://spreadsheets.google.com/pub?key=p8SIY47PNEw4vx1GOsJM7bA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFJTUEVleTM0cE5jTnlTMk41ajBGclE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdDBuUVIzbWwtaU5helpJVG5BMmxyX1E&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdDJxdlN6cEtYMjMxdC1XdGdKOXR2bkE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHZSTVMxaVdxQlFLR3NMbnBEWnVuTXc&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEddLKU1fnfSSA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdQY2PxSsxxJQ&output=csv", 
"http://spreadsheets.google.com/pub?key=t1YAVXUoD3iJKy2mSq2Padw&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdDhjcXdjbURLMFFVcVFPYThhYmtvZXc&output=csv", 
"http://spreadsheets.google.com/pub?key=ryPd-H6Kn3wcHC50zyImqUg&output=csv", 
"http://spreadsheets.google.com/pub?key=r4WUTsck3NfccM6UsKlGF7g&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldEJZajRXMWZPTE9nUXFBNUdPcG5yT2c&output=csv", 
"http://spreadsheets.google.com/pub?key=rW7k_DdDKlGgJhzYRuNvguw&output=csv", 
"http://spreadsheets.google.com/pub?key=rraOr_PTB0jcQ60TagEH_WQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rjFKVVoWIVbTgdtJK2xOZqQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rA5BvUGX_Es43DaKb3FidUg&output=csv", 
"http://spreadsheets.google.com/pub?key=rT5EpK40a19zVodp1HV1xGw&output=csv", 
"http://spreadsheets.google.com/pub?key=t6nZVbvqsF-BbyheqUxerZQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rhuyv42EAyApMwy4tDYm3XQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rIe2Y4f4Ehde4I4BGPN2VBg&output=csv", 
"http://spreadsheets.google.com/pub?key=r1B3mjfpBItUmvrhqaRgTWQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rOXvRa2ZC2oXqBn7gz62IMg&output=csv", 
"http://spreadsheets.google.com/pub?key=rZyHDNFsPBn7cqZCIzDQtIg&output=csv", 
"http://spreadsheets.google.com/pub?key=rcHjAQAzF2e1yR1R-hywCEw&output=csv", 
"http://spreadsheets.google.com/pub?key=rRS0FbArN8jYsY25X-ZiU9A&output=csv", 
"http://spreadsheets.google.com/pub?key=rMf--YMvuEKf2LVppT63Xvw&output=csv", 
"http://spreadsheets.google.com/pub?key=rLRScmH2JZmjxsCGW2LB1cA&output=csv", 
"http://spreadsheets.google.com/pub?key=rgdYcit5cC0wxcLAQf9kJ_Q&output=csv", 
"http://spreadsheets.google.com/pub?key=r9StWVETzyX9Lv-r4-2sh6w&output=csv", 
"http://spreadsheets.google.com/pub?key=rz8kJ7CIyckuQAWgHUHe4sA&output=csv", 
"http://spreadsheets.google.com/pub?key=rEZ0xOSmU7UuX7iOyL0Xp3g&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcfLoOcU6GAfg&output=csv", 
"http://spreadsheets.google.com/pub?key=rsCDusOObseaoBUdarzw7Kw&output=csv", 
"http://spreadsheets.google.com/pub?key=rtESPUlrTyLEoHpURqE8RAg&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGlYVVpXX20tbU13STZyVG0yNkRrZnc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdE03VFhRMnBpMGZhQ19Vbk9pMGU5VUE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHQtSzBhVXA2WTNrVDFleUZvZ0doTUE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFRuaV91Mm9JeUhwR1hHRXJhV3ZBQkE&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWfRGgfhjf8FBQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWeB1N1HlpFQVQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWd9CVdfFx1dEw&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWf66stZ2oNUAA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHo5S0J6ekhVOF9QaVhod05QSGV4T3c&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEdDWHhBcFpjMUo4MGE2X2Q4WXFQRGc&output=csv", 
"http://spreadsheets.google.com/pub?key=tvllZwGIbhwxLD7EXFhPeXQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rcTO3doih5lvJCjgLSvlajA&output=csv", 
"http://spreadsheets.google.com/pub?key=r6kTHMinnVedj8gPsUtfZ0g&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFVrVDZQUnRwZ2lqT2lPMXcySXZwRmc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFdqZ0NOdjluMmoyUTBTWTRjWWQzQVE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGhJcHAwanc2aFdZeXl1WTVZQnJjb1E&output=csv", 
"http://spreadsheets.google.com/pub?key=t3IAEOsfHK-z6rvGLCDR74g&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEd7K-YgYOkGFQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tZ3uHUdw0H__Siyj78GXsGg&output=csv", 
"http://spreadsheets.google.com/pub?key=tBwBBkViOJoycBhLnWHqwSQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcJI3KBJnrlDQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tyadrylIpQ1K_iHP407374Q&output=csv", 
"http://spreadsheets.google.com/pub?key=tRybjVoG5Ah9yhKcEx16u5Q&output=csv", 
"http://spreadsheets.google.com/pub?key=t7pU8fR9_ZzRFIMF3FX47YQ&output=csv", 
"http://spreadsheets.google.com/pub?key=thClNiXoQqfJDzTv0SYIHZg&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEZkTFJZR2RNMVFuRmUzbktyTkoxREE&output=csv", 
"http://spreadsheets.google.com/pub?key=t4C4M_ynK9Ho8tGRj6a5U5w&output=csv", 
"http://spreadsheets.google.com/pub?key=tQe6yinBBauXLvBFroZEL3Q&output=csv", 
"http://spreadsheets.google.com/pub?key=rEF20Sw6Sy7tn4DKsKSDDMQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rAIffGKCmiCdzTl1C0AR2nw&output=csv", 
"http://spreadsheets.google.com/pub?key=tSjVrGemv30eCh3jPZkXYCQ&output=csv", 
"http://spreadsheets.google.com/pub?key=t1MShlv870O6LmFNEHazdEg&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdHFkZlc5WkhVQmVmeU0tR0RsSUdTU0E&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEhLMVdnUjZ0d05WWkhjT0FjSDIwQmc&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcL6zpB3Sj1Wg&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdE4tekJPYkR4WmJqYTRPWjc3OTl4WUE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFNPMTE3d3FHTHdYaGFMXzJyNDBGd3c&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfLbPu48DrKfQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEd98lRwrU3gIg&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFhhVzhXUEh0U0hlQ3M3TTZIQTFySUE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdDlJNzNjcVc5Sm9memNuVHRzY1FsOXc&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1jiMAkmq1iMg&output=csv", 
"http://spreadsheets.google.com/pub?key=rX3Jfop_ebuY-chuMpCgmRg&output=csv", 
"http://spreadsheets.google.com/pub?key=tXRyZGCfHsWMmr53VFxrqTw&output=csv", 
"http://spreadsheets.google.com/pub?key=twSOUYrIFh2W2snDUt7VaQg&output=csv", 
"http://spreadsheets.google.com/pub?key=t_-14NtXH6xZX48xHG75z5w&output=csv", 
"http://spreadsheets.google.com/pub?key=trzLWJQU4SZMDpeVg3XnL5A&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdIyrBS31XAaw&output=csv", 
"http://spreadsheets.google.com/pub?key=tmKvydPl_roGIQBrMYA6C4g&output=csv", 
"http://spreadsheets.google.com/pub?key=tLnCxItXzRSu9gH-5PyEFDw&output=csv", 
"http://spreadsheets.google.com/pub?key=rGKP-BBylLOM11iGahW1lxA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHA2UEFOYTlUTWtzV29xbHFuMU00SFE&output=csv", 
"http://spreadsheets.google.com/pub?key=rqcJTExcUqNdolB-7flqebQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcjeKHnZq6RIg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0NpF2PTov2Cw&output=csv", 
"http://spreadsheets.google.com/pub?key=rDb6EYc4YUTBRfXlBvjHYlg&output=csv", 
"http://spreadsheets.google.com/pub?key=rjGHot8B6YSt3kPYEG8nANA&output=csv", 
"http://spreadsheets.google.com/pub?key=rVyfxaPK4dJ9B6ZdgG34F-g&output=csv", 
"http://spreadsheets.google.com/pub?key=r0pD5wznwEUJ0ipdxAWQjiA&output=csv", 
"http://spreadsheets.google.com/pub?key=rOPfJcbTTIyS-vxDWbkfNLA&output=csv", 
"http://spreadsheets.google.com/pub?key=rcbx0R-TXbkqRCyvKzn08fg&output=csv", 
"http://spreadsheets.google.com/pub?key=rewICFMTvBuer8UoJIK0yUg&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdGJoOUJXalk3STFYUG85MkxlbnQxMmc&output=csv", 
"http://spreadsheets.google.com/pub?key=tfOi0Ji7pJDJbxJVqwJXj9g&output=csv", 
"http://spreadsheets.google.com/pub?key=tnRIpcH0InZUFz7f2ziXKog&output=csv", 
"http://spreadsheets.google.com/pub?key=riLRFECHMsTq7OTa2KYZCWA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdGwzSGV5OE9FOGhURlhTdEQtMW1TNkE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdC1PcWJUZldDelFyQXdaOEtDUG9HSUE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdG9sVVF6dHpGdnhQU3BkMlAtNHFwVkE&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2tPLxKvvnNPA&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdG9jSHA0WklHU0dqUnBCVUpVOXFzQUE&output=csv", 
"http://spreadsheets.google.com/pub?key=tiAiXcrneZrUnnJ9dBU-PAw&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEc96gAEE60-Zg&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEd4fn4YYOvuOg&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdrsBnj2ROXAg&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEf96wv_abR0OA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEe7OxrqKcSWfw&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEepmgV0TLjBag&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3rojF8TmZtOw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2ItBsVpK9VBA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1u0KpZbsopCA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2xhaKENmyRKw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2LwNOwMSnJQA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1RD88c3w1vNg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1_IYQtrqQCKQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2LIYJXVW9EVw&output=csv", 
"http://spreadsheets.google.com/pub?key=rCRqVXC95LeKm_EvLrFNXKw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2_ibAjsuNgYA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2hZorcv6aVLA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1kCRbsnNcTVg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0UaQ2DNjK9Lg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0RMyUI1QFfaA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2Az43qu-dQJQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2oQAW8_53cVQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0sd0z2MGpeeA&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWcGnFB9pe14OA&output=csv", 
"http://spreadsheets.google.com/pub?key=tunqKEwokfnJMDA1g7W8KwA&output=csv", 
"http://spreadsheets.google.com/pub?key=t1Vf-4rkGlG20pYzuGib3hw&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWfGZUVJ2L-dCw&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWczfPHQMiqxCg&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWfZGL9qouvTbQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rtt_ihBgyYafmDJpThQecoA&output=csv", 
"http://spreadsheets.google.com/pub?key=rJMlhr2YOvL2EE5NhpbfYAg&output=csv", 
"http://spreadsheets.google.com/pub?key=rmLnlLnnm2kjBbNsBZYxqow&output=csv", 
"http://spreadsheets.google.com/pub?key=rezDaYxOOBEFgR4TiPN9qtw&output=csv", 
"http://spreadsheets.google.com/pub?key=tZMsbTkrY0k4OkkkXEfp6pA&output=csv", 
"http://spreadsheets.google.com/pub?key=riwXFQrsUhb96BT2yFC9rFw&output=csv", 
"http://spreadsheets.google.com/pub?key=raAOA9AFRPzq5ilAm5Qa65Q&output=csv", 
"http://spreadsheets.google.com/pub?key=ravxsZdBslM5zF5HwDsX30g&output=csv", 
"http://spreadsheets.google.com/pub?key=rTRt7Z5m9i9D9-vvipvdx2w&output=csv", 
"http://spreadsheets.google.com/pub?key=rImcpLhokI0fXWNA-2nSWFw&output=csv", 
"http://spreadsheets.google.com/pub?key=r5_68IYi0bC1bRjGMFYFk8g&output=csv", 
"http://spreadsheets.google.com/pub?key=rCyfwvThkbHVlNVw48vHybg&output=csv", 
"http://spreadsheets.google.com/pub?key=rGS7_GpdXrYyjhKkAFcLHGA&output=csv", 
"http://spreadsheets.google.com/pub?key=rB4P-M5oVWuv9CyQ5s1mvOA&output=csv", 
"http://spreadsheets.google.com/pub?key=rj102tw9R1O_d56Uw_eqBzg&output=csv", 
"http://spreadsheets.google.com/pub?key=rjkDFSPV2pw9Pbnz2kpiqPQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rSMPg9BmVRsqE8_k1ARUudA&output=csv", 
"http://spreadsheets.google.com/pub?key=r_hbrX2qsjHphzAAlwsxhRA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdGhpWDY5QVlOdUxpVGhaMVlUOE9iX0E&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfMkeuokDLVIQ&output=csv", 
"http://spreadsheets.google.com/pub?key=t2ha4jg1M70Le8CH3wHcPIQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tOJs331rbt36sNBXE8g5AUg&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcVezxiMlWaRw&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdE5UaXVKa2hWbUFzcUJJbVdHOE1VcFE&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3Iw3kqbjJTZQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3fwfA8XA25Eg&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEenS18Yjl_SOQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdHlYZHNWN1YtWVNudU9UbWJOd19nUVE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdC03X1ZWNGJHR3FBb0Q3VjJIdV9OSmc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdG5JUDZjTHR5SzZFZjBqa2JYYUxBclE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdC1MYzAtY2xPQ2xOR1lMeGhYSWlpR0E&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdHFEVVhHZElzb0VRWE9pc3JmZHg2dWc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdEttYjNNUTlkUTdrMUQ0c3BTR0dINlE&output=csv", 
"http://spreadsheets.google.com/pub?key=tfyKUbGu10P_WOgHSOHhCJg&output=csv", 
"http://spreadsheets.google.com/pub?key=tYZAce4wGXEp5Jve3AI7yWQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tH113JLeGr5DhWgtqN2FxWg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2yo1IzJQmbZg&output=csv", 
"http://spreadsheets.google.com/pub?key=tZhYsw0sliDInwowT0iWTLQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tX-vHLzEZ7mqfk1vf6SbUXA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdDJFSzRHa3g1Q29BOWlla0tTOEFyVGc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdDNPQjFBT2s5Zko3U2V0NFQzS3owRnc&output=csv", 
"http://spreadsheets.google.com/pub?key=t7-m0musxnWbugcQ9ECH4KA&output=csv", 
"http://spreadsheets.google.com/pub?key=tBJ1rYQ-nA6fqI6_Gn3mBNg&output=csv", 
"http://spreadsheets.google.com/pub?key=r58mA3XNUvBov6M_1T_FiUg&output=csv", 
"http://spreadsheets.google.com/pub?key=ruUmTRBZ5xYjpOAhOT9VQbw&output=csv", 
"http://spreadsheets.google.com/pub?key=tZgPgT_sx3VdAuyDxEzenYA&output=csv", 
"http://spreadsheets.google.com/pub?key=tIgjxaAg3M6kuHRcQTjEgsQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldDFGSGhtOWt0cS1JbEIzS29EZzlQRXc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldG51d0o2T0JQWXFTMUlydWFsSTZMeFE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldElCSWl6TkpaZ1JpcXVxa2tmUGhxbFE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldGF1WHhpZFVQTWswclJHdjE3MkZ4c3c&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldC1rcTI5OU50Mnc1djdkNXpnWUFrZmc&output=csv", 
"http://spreadsheets.google.com/pub?key=tHgVOu-6TYQ6Kig0Ur3Y-kw&output=csv", 
"http://spreadsheets.google.com/pub?key=tyeSLo9Zpmw_e05IR3EoReg&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEf0IBo_AGrgKA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfv2K6dZmskWg&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEc5qiv87tr3NA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfZd6DbNF1MKA&output=csv", 
"http://spreadsheets.google.com/pub?key=tqAEpy6pMtN7ULlF6uIzEog&output=csv", 
"http://spreadsheets.google.com/pub?key=tfmFGk3PIvTgimegQiHOtSQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEe5SueBIj6eSw&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdERQeFplM2VWczVrMTFfMXVrQkJpVXc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdDREUkRSRDJtQmFNTE1TYmRYX1pFNEE&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFk2WGhwakxTQkt4NUtTdFJDSlFHQ3c&output=csv", 
"http://spreadsheets.google.com/pub?key=t28UhT9IaWINamciSiJIS7w&output=csv", 
"http://spreadsheets.google.com/pub?key=trRb8ZIaBOD4KzikShshZ2g&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGhSY2trbEVpYnNsMENqendaVm5ucnc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdERNZmlfUGM5YVE3bmEwODdlRDFqSkE&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcm0fIa0IVtKw&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEeUgUuvuJTONQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdNIa3ckVXaCQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfJfS1WYrLeBA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfrI4YlDJDUag&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0npaJxInyYDg&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdE5xWmcyYVZJQzJvOFpZUklqX3lkSkE&output=csv", 
"http://spreadsheets.google.com/pub?key=tiYIen5OQP0fKiQbg6g8VyA&output=csv", 
"http://spreadsheets.google.com/pub?key=tyPO4OLCIZtK5zcdkafcHMA&output=csv", 
"http://spreadsheets.google.com/pub?key=tVAqgYwCDZfcq9jSCI87SAw&output=csv", 
"http://spreadsheets.google.com/pub?key=tiehFos6jB-lekEAH028deA&output=csv", 
"http://spreadsheets.google.com/pub?key=tqjUijP4mi_dHKkCZjOn0oA&output=csv", 
"http://spreadsheets.google.com/pub?key=tXf6_OUYVmyEMZo0g4DQw6w&output=csv", 
"http://spreadsheets.google.com/pub?key=tnvxVX8aOAl0dwDNujbELPQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEd5FA9xlfO9eA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdMioz5VJKXHw&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEe371ZVZl73eA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEe1GaiYJX2qGA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdFW4nUY4gQdA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfUXdC83YSzfw&output=csv", 
"http://spreadsheets.google.com/pub?key=t4RbfeK6Dtt2srxw4REoXxQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tdOlzqGxVdDnnCpfWyyGX1A&output=csv", 
"http://spreadsheets.google.com/pub?key=rhbS3kWOfMzvY4ofUFoeFJg&output=csv", 
"http://spreadsheets.google.com/pub?key=rSv5aMDwESiKg-yA__-tRFg&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWc4aJd9fV8zZg&output=csv", 
"http://spreadsheets.google.com/pub?key=tCe8N5KXAYCJteQokAqVM_A&output=csv", 
"http://spreadsheets.google.com/pub?key=tcYkTk6KMHsrXzcM9WyUxbw&output=csv", 
"http://spreadsheets.google.com/pub?key=tOXHWd6PcUGK3Dg-k2N8Clw&output=csv", 
"http://spreadsheets.google.com/pub?key=tjvbVGhVx7YCk1uguLrkaag&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldGhVLXVsSTB0aDY2eXdLaEt1T0psdXc&output=csv", 
"http://spreadsheets.google.com/pub?key=rovrK0Uj9JPN95P9adob0tw&output=csv", 
"http://spreadsheets.google.com/pub?key=rsOONWhmGBtzb4j__0MJv7Q&output=csv", 
"http://spreadsheets.google.com/pub?key=roLpNPQkooNCFzpTWXQ48Dw&output=csv", 
"http://spreadsheets.google.com/pub?key=rIpDsoI9lVTCh_PRqm66Tcw&output=csv", 
"http://spreadsheets.google.com/pub?key=r9ztOSMb5WNHUBLwlgJqPSw&output=csv", 
"http://spreadsheets.google.com/pub?key=rmViJSkPd4xZneV2Q6gzFwQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rJwVmwTFzheqVUzYWwSqXlA&output=csv", 
"http://spreadsheets.google.com/pub?key=rmQZ_H88rIhF3315QBZpcIQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rFmJvuotJYE30q4nWEvpGJA&output=csv", 
"http://spreadsheets.google.com/pub?key=r4VUu4a4AaWqXXoAsFz-z-Q&output=csv", 
"http://spreadsheets.google.com/pub?key=rYEHWlJHaLjHtcsSpRRJeig&output=csv", 
"http://spreadsheets.google.com/pub?key=rYfw4UJZSizLRtgDs73d5jA&output=csv", 
"http://spreadsheets.google.com/pub?key=rHrin819tHgZudARnpsN0Mg&output=csv", 
"http://spreadsheets.google.com/pub?key=rTU20DXn0Bi7bTwW5T6J3gg&output=csv", 
"http://spreadsheets.google.com/pub?key=rWpQHQIQdntj6BEK8OIuWYw&output=csv", 
"http://spreadsheets.google.com/pub?key=rab1GmqpzJkWd4MF0hieVgA&output=csv", 
"http://spreadsheets.google.com/pub?key=ri9SXMNc7TpebHucmAYepGQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rLwpdKbW2OykBbvVxhYKrhA&output=csv", 
"http://spreadsheets.google.com/pub?key=rElErbmOnSM6om03a1uinKQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rcQkob1yAm-to1scz51flgw&output=csv", 
"http://spreadsheets.google.com/pub?key=r83X3yfjC6ENYWoo41yDehg&output=csv", 
"http://spreadsheets.google.com/pub?key=rC5UskPU6PRVlmN7eXoridw&output=csv", 
"http://spreadsheets.google.com/pub?key=re3efChATTYAT5bRqoaChXA&output=csv", 
"http://spreadsheets.google.com/pub?key=rgyZrNmSfXcPJQxJK7IxnEw&output=csv", 
"http://spreadsheets.google.com/pub?key=rVD6A2uAmeIE0BQNW1KSg3A&output=csv", 
"http://spreadsheets.google.com/pub?key=rH6TEe8f_WNq_8x9pWZ3W0A&output=csv", 
"http://spreadsheets.google.com/pub?key=rjhBvpeRgCxBq0EnQVN6b0w&output=csv", 
"http://spreadsheets.google.com/pub?key=rSkhGgUVN74knEhSAhBSSKA&output=csv", 
"http://spreadsheets.google.com/pub?key=tVY51lNaCL9m9xPqf29oFAA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFY5Z0QzTzRRbzJ1VXdqdGVyNE0tcFE&output=csv", 
"http://spreadsheets.google.com/pub?key=rZrHzR__kZfmw6L_xUx7cwg&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdwXv1tqzV4Xg&output=csv", 
"http://spreadsheets.google.com/pub?key=tjFf_YqwB6tgSG9L0r0Ywdg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0XOoBL_n5tAQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tBrbR3BlR_12WlTIlSTpu6g&output=csv", 
"http://spreadsheets.google.com/pub?key=tVMPnbOfGdvTRrtbuIbRw5w&output=csv", 
"http://spreadsheets.google.com/pub?key=tVyFL3CyRTuGEnRQErDeSLQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEeUceHo3wTOaQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEhTN2hlZ05ZczVwZDdVZlF5cUxJb2c&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWeECA6Gf__BNQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdGhCWnZrTGMwaTl5ek9QS0szMTIwcEE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFVxSEVZVWE1b0l6NWo5NzNTZ2IzWVE&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcXBFxQw8cFaw&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWdFemmS_iN5fw&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWdtCylhQOQiXw&output=csv", 
"http://spreadsheets.google.com/pub?key=tMjW0fdVf9VJaxVk_VFSUhg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2S9phBhTP3dw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3qX39HWaQjEg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1ImYURLRHPRA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2vXUZJKI0XHA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdz8B4njtoHPA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcWM3hb0x-BZA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdE8xR0dUWDI4ME02SjQ5bi1NYnFHN0E&output=csv", 
"http://spreadsheets.google.com/pub?key=rPN9VekxwpUzwowMaxg9Ybw&output=csv", 
"http://spreadsheets.google.com/pub?key=t7SFNscT9Ex0s9i3av7PxRQ&output=csv", 
"http://spreadsheets.google.com/pub?key=teUZEfKw52HewO3D0YrQ5HA&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdEV1RkJqTEItQnJYVXJlZzVuc3Y3Mmcnn&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdDBKd2V5VmxkYlJuUHAtOURzUkZzNEE&output=csv", 
"http://spreadsheets.google.com/pub?key=trbzCrl1eb6QJG5D8j1-qQw&output=csv", 
"http://spreadsheets.google.com/pub?key=rcO6CXqmEjV-wS-29qejCpw&output=csv", 
"http://spreadsheets.google.com/pub?key=rSrvaPPzWvOyTMb9_dfJDtQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tGVRSoAJtdwQ30CqCSexKJA&output=csv", 
"http://spreadsheets.google.com/pub?key=tRA1VmW2ZQ7sCsoD7AHIilg&output=csv", 
"http://spreadsheets.google.com/pub?key=r4orIwujZpT-z3Exd_9ARpQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdHk4eXd4RG5Rb1gtUTB0cUJ3M21qdGc&output=csv", 
"http://spreadsheets.google.com/pub?key=tfWSVJPJHn3u7e_7MUaCbnw&output=csv", 
"http://spreadsheets.google.com/pub?key=ta-Da73B_Z7lKOZo8o-Ykvw&output=csv", 
"http://spreadsheets.google.com/pub?key=tF_P_4G0g5bR3lYmQT9Tv4w&output=csv", 
"http://spreadsheets.google.com/pub?key=tQP1KnoWcjjtz3wmq0bnGNA&output=csv", 
"http://spreadsheets.google.com/pub?key=tAQ31_cAELrHqNc2qa13uHw&output=csv", 
"http://spreadsheets.google.com/pub?key=tRccVp7QMaCXMv19CcxERaA&output=csv", 
"http://spreadsheets.google.com/pub?key=t60tpjxpWq3Bm-nBOvSm3og&output=csv", 
"http://spreadsheets.google.com/pub?key=thortPEzDn2xc_5bU255mPA&output=csv", 
"http://spreadsheets.google.com/pub?key=tgJHpDEY4S7hxJpELGJueWA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3ky4_oAkatBw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0RpUEQPgGcZQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1XKvT6zwrMPw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0je8zzeM4WXQ&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1o1rJNFHpQZw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2NmCvOcsjpag&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1aXfw3aV83TA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3XF3cD2lbecA&output=csv", 
"http://spreadsheets.google.com/pub?key=rAxnmm4ZL2HrYjIqJX0Ch-w&output=csv", 
"http://spreadsheets.google.com/pub?key=r0JePjBgBQqtuh5wh1Wz9CA&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdGlGLVd4OGVfcVdScVBSS0JLVHpiMlE&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2sdmdhX9zuKg&output=csv", 
"http://spreadsheets.google.com/pub?key=troMumuI0Y6Phpwnj6qXa_A&output=csv", 
"http://spreadsheets.google.com/pub?key=tOS388dWYzO1_FANUaiwKuA&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldGhJdkhTSHNEYTFKQjRrMlBwZXk1TkE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldHNWNkNVR2Zwalc2U04zTjE5MDZlUkE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldG9MeHpzRkNHQmZ4MmtxSnd2Y0o2UFE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldGh2OWd2eVJiUnhScW9tOEtNTFkyQUE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldEVRNFBZS2wzRmtZOWZEZDVZVG05dHc&output=csv", 
"http://spreadsheets.google.com/pub?key=tB8ge4cxd8TL7yIV4ALm5NA&output=csv", 
"http://spreadsheets.google.com/pub?key=tUD6kmYmB_Bp85SRdEn1Krg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0uBndTxZAXNQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFFWcWdEM0RXT1lRZ0wwRVNsakZCaWc&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArtujvvFrPjVdGdFWmhqOEVXcUZha1hJWXAtWHlDSFE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFgzT1ZJWW4tdDB4Q2NETTVoTG1ZYlE&output=csv", 
"http://spreadsheets.google.com/pub?key=rKfjGaPxqirPDe8gnTVKuIw&output=csv", 
"http://spreadsheets.google.com/pub?key=rUBCConMMLm9CxPXUGm325A&output=csv", 
"http://spreadsheets.google.com/pub?key=rQV47xgPGa3qOPHoLiVon-w&output=csv", 
"http://spreadsheets.google.com/pub?key=rRCxDI3hB9E9zvc8qSe11qg&output=csv", 
"http://spreadsheets.google.com/pub?key=rFAkC0Ae7oXxrVqosJ4NWUA&output=csv", 
"http://spreadsheets.google.com/pub?key=reiGJwoabnMOrPeFima_9ng&output=csv", 
"http://spreadsheets.google.com/pub?key=rERPF4iYruK0DhAw_0tb5nA&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEdIphYUHxcdLg&output=csv", 
"http://spreadsheets.google.com/pub?key=t1E7e32tlIxtJU9UhnR9nJg&output=csv", 
"http://spreadsheets.google.com/pub?key=tB6Gkh4rLC9yB2TXfHSApIA&output=csv", 
"http://spreadsheets.google.com/pub?key=0Asm_G8nr4TCSdDh2NWQtVDJhYlVsTElFRjJIYkNlSnc&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfI4sLVvEQtHw&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdFl6cDkxcmZxM0pVNXBUYjE1ZmNqVUE&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj3XYThRy0yJMA&output=csv", 
"http://spreadsheets.google.com/pub?key=tR3MM-UTZ0B44BKxxWeAZaQ&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEeL79qOoKtofQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tNWhbu-1UIPPxtmRHtnINOQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tL0jLxFBF9TbXIN_39b1qcQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdC1iMVRuVUFUd08tVDM0ZDF0cnFtekE&output=csv", 
"http://spreadsheets.google.com/pub?key=t9SYWh7siLJDzyZYN1R4HfQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rIG3ZWxv381t2bIL2BNaIVw&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdFpGU185SkpmZ2V4ajNPZHFaaEwtU1E&output=csv", 
"http://spreadsheets.google.com/pub?key=0AkBd6lyS3EmpdEF6VzlKTzNCNjRnT0ZzMDg5a1d1Z3c&output=csv", 
"http://spreadsheets.google.com/pub?key=tW9t1f9EQpvS4U04kWnk-og&output=csv", 
"http://spreadsheets.google.com/pub?key=tK87SOy-oZlfW99UDD7L3hw&output=csv", 
"http://spreadsheets.google.com/pub?key=tUaaG6Pu9zT_BVIsLvGLQdA&output=csv", 
"http://spreadsheets.google.com/pub?key=t4pYrpNzP-JeR7zSjOyDofQ&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldEVPSG5qYzBfS0llQ1RnTl9wWXZodkE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldGRqbENsQm5VMWFLdnRXV0w1S0tVSEE&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldFJrcW9wdlJITlBDYU9IbnRKdVllVGc&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldEw5RXhuckZuU1V2aVAzNDFZaDUxa2c&output=csv", 
"http://spreadsheets.google.com/pub?key=0AgogXXPMARyldHB2MkhmVDcyMG1Oa3Y5eEhRQ0VlUWc&output=csv", 
"http://spreadsheets.google.com/pub?key=rskN46tpbe6Iy3K_ULk1_cQ&output=csv", 
"http://spreadsheets.google.com/pub?key=rdBew79hTeXcIXhB1VCTPfg&output=csv", 
"http://spreadsheets.google.com/pub?key=p8SIY47PNEw6pJRPAS1tXPQ&output=csv", 
"http://spreadsheets.google.com/pub?key=p8SIY47PNEw4TgTkrmIVIXA&output=csv", 
"http://spreadsheets.google.com/pub?key=0ArfEDsV3bBwCdDdTQUtvNEJhb0RjRjU0WUtET1R0Vnc&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEfH89V6UQhpZA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj0-LE4StzCsEw&output=csv", 
"http://spreadsheets.google.com/pub?key=pyj6tScZqmEcRJEN8MyV3PQ&output=csv", 
"http://spreadsheets.google.com/pub?key=tublssyj-uqIY25OoRupbCw&output=csv", 
"http://spreadsheets.google.com/pub?key=tXn3DSfvsYujaBP9bvH6acg&output=csv", 
"http://spreadsheets.google.com/pub?key=rezAT4nYhKc2Loe6CxWSPWw&output=csv", 
"http://spreadsheets.google.com/pub?key=pp59adS3CHWe8O-N9RgxzDw&output=csv", 
"http://spreadsheets.google.com/pub?key=rdCufG2vozTpKw7TBGbyoWw&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj2t4ep52YXjSg&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj02SA7cGjnRbA&output=csv", 
"http://spreadsheets.google.com/pub?key=phAwcNAVuyj1NHPC9MyZ9SQ&output=csv"
)), .Names = c("indicator", "provider", "category", "subcategory", 
"link"), row.names = c(NA, 519L), class = c("tbl_df", "tbl", 
"data.frame")) -> gap_data
